logging:
  level:
#    org.springframework: DEBUG
    org.springframework: INFO

spring:
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch
    username: root
  batch:
    initializer:
      enabled: true
    initialize-schema: always
    job:
      enabled: true
